import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart,
  Bell,
  Brain,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Code,
  Copy,
  Command,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileText,
  HelpCircle,
  Home,
  Image,
  Laptop,
  Lightbulb,
  Link2,
  Loader2,
  Mail,
  MessageCircle,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Save,
  Target,
  TrendingUp,
  TrendingDown,
  X,
  XCircle,
  Info,
  RefreshCw,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Star,
  SunMedium,
  Trash,
  Twitter,
  User,
  Wallet,
  Zap,
  LineChart,
  Key,
  BarChart3,
  Activity,
  Sparkles,
  Headphones,
  MessageSquare,
  Globe,
  Layers,
  FileBarChart,
  Users,
  Coins,
  Stethoscope,
} from "lucide-react"

export type IconProps = React.HTMLAttributes<SVGElement>

export const Icons = {
  // Iconos básicos
  logo: Command,
  close: X,
  xCircle: XCircle,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  copy: Copy,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  externalLink: ExternalLink,
  file: File,
  fileText: FileText,
  image: Image,
  twitter: Twitter,
  check: Check,
  checkCircle: CheckCircle,
  search: Search,
  analytics: BarChart,
  social: Share2,
  code: Code,
  reset: RefreshCw,
  refresh: RefreshCw,
  content: FileText,
  
  // Iconos personalizados para tu aplicación
  metadata: Database,
  blockchain: Layers,
  ai: Sparkles,
  placeholder: Command,
  
  // Iconos para herramientas SEO
  keywords: Key,
  links: Link2,
  performance: Activity,
  competitors: Users,
  reports: FileBarChart,
  
  // Iconos para Web3
  wallet: Wallet,
  "social-web3": Globe,
  
  // Iconos adicionales
  dashboard: Home,
  home: Home,
  token: Coins,
  download: Download,
  lightbulb: Lightbulb,
  success: ShieldCheck,
  email: Mail,
  discord: MessageSquare,
  support: HelpCircle,
  info: Info,
  sparkles: Sparkles,
  alert: AlertTriangle,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  target: Target,
  star: Star,
  stethoscope: Stethoscope,
  database: Database,
  shield: Shield,
  globe: Globe,
  coins: Coins,
  layers: Layers,
  zap: Zap,
  loader: Loader2,
  bell: Bell,
  save: Save,
}